
### Login to get authentication cookie
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "koko@gmail.com",
    "password": "12345678"
}

### Add item to cart
POST http://localhost:5000/api/cart
Content-Type: application/json

{
  "productId": "67557ba27a88cdd6f25df541",
  "quantity": 2
}

### Get cart items
GET http://localhost:5000/api/cart

### Update cart item quantity
PUT http://localhost:5000/api/cart
Content-Type: application/json

{
    "productId": "67557ba27a88cdd6f25df541",
    "quantity": 2
}

### Remove item from cart
DELETE http://localhost:5000/api/cart/675621e13895e58b7862369c 


### Clear entire cart
DELETE http://localhost:5000/api/cart